### ISSUE TITLE
Background color is not printed

### ISSUE THREAD

**Issue by HugoDerigny** [Wawa27/react2pdf#1]
When using CSS background property, it is not set.

The fix would be to use 
```js
await page.pdf({
       ...
        printBackground: true
});
```

If it dont solve the problem, add this css style property :
```css
html {
  -webkit-print-color-adjust: exact;
}
```

**Ref:** [https://stackoverflow.com/questions/60736354/puppeteer-not-rendering-color-background-color-when-i-try-to-save-pdf-on-disk](https://stackoverflow.com/questions/60736354/puppeteer-not-rendering-color-background-color-when-i-try-to-save-pdf-on-disk)

**Comment by Wawa27** [comment]
fixed using render options see 8f2a41ce0053b9557199aa3e49489c10f486b5b4 and pdf option "printBackground" : https://pptr.dev/api/puppeteer.pdfoptions
